from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget, PlotItem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 285, 540, 150))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        self.verticalSlider = QtWidgets.QSlider(self.splitter)
        self.verticalSlider.setEnabled(True)
        self.verticalSlider.setMinimum(0)
        self.verticalSlider.setMaximum(10)
        self.verticalSlider.setSingleStep(1)
        self.verticalSlider.setProperty("value", 1)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")

        self.verticalSlider_2 = QtWidgets.QSlider(self.splitter)
        self.verticalSlider_2.setMinimum(0)
        self.verticalSlider_2.setMaximum(10)
        self.verticalSlider_2.setSingleStep(1)
        self.verticalSlider_2.setProperty("value", 1)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")

        self.verticalSlider_3 = QtWidgets.QSlider(self.splitter)
        self.verticalSlider_3.setMinimum(0)
        self.verticalSlider_3.setMaximum(10)
        self.verticalSlider_3.setSingleStep(1)
        self.verticalSlider_3.setProperty("value", 1)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        
        self.verticalSlider_4 = QtWidgets.QSlider(self.splitter)
        self.verticalSlider_4.setMinimum(0)
        self.verticalSlider_4.setMaximum(10)
        self.verticalSlider_4.setSingleStep(1)
        self.verticalSlider_4.setProperty("value", 1)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setObjectName("verticalSlider_4")

        self.verticalSlider_5 = QtWidgets.QSlider(self.splitter)
        self.verticalSlider_5.setMinimum(0)
        self.verticalSlider_5.setMaximum(10)
        self.verticalSlider_5.setSingleStep(1)
        self.verticalSlider_5.setProperty("value", 1)
        self.verticalSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_5.setObjectName("verticalSlider_5")

        self.verticalSlider_6 = QtWidgets.QSlider(self.splitter)
        self.verticalSlider_6.setMinimum(0)
        self.verticalSlider_6.setMaximum(10)
        self.verticalSlider_6.setSingleStep(1)
        self.verticalSlider_6.setProperty("value", 1)
        self.verticalSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_6.setObjectName("verticalSlider_6")
        
        self.verticalSlider_7 = QtWidgets.QSlider(self.splitter)
        self.verticalSlider_7.setMinimum(0)
        self.verticalSlider_7.setMaximum(10)
        self.verticalSlider_7.setSingleStep(1)
        self.verticalSlider_7.setProperty("value", 1)
        self.verticalSlider_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_7.setObjectName("verticalSlider_7")
        
        self.verticalSlider_8 = QtWidgets.QSlider(self.splitter)
        self.verticalSlider_8.setMinimum(0)
        self.verticalSlider_8.setMaximum(10)
        self.verticalSlider_8.setSingleStep(1)
        self.verticalSlider_8.setProperty("value", 1)
        self.verticalSlider_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_8.setObjectName("verticalSlider_8")

        self.verticalSlider_9 = QtWidgets.QSlider(self.splitter)
        self.verticalSlider_9.setMinimum(0)
        self.verticalSlider_9.setMaximum(10)
        self.verticalSlider_9.setSingleStep(1)
        self.verticalSlider_9.setProperty("value", 1)
        self.verticalSlider_9.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_9.setObjectName("verticalSlider_9")

        self.verticalSlider_10 = QtWidgets.QSlider(self.splitter)
        self.verticalSlider_10.setMinimum(0)
        self.verticalSlider_10.setMaximum(10)
        self.verticalSlider_10.setSingleStep(1)
        self.verticalSlider_10.setProperty("value", 1)
        self.verticalSlider_10.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_10.setObjectName("verticalSlider_10")

        self.splitter_1 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_1.setGeometry(QtCore.QRect(570, 270, 95, 190))
        self.splitter_1.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_1.setObjectName("splitter_1")

        self.verticalSlider_11 = QtWidgets.QSlider(self.splitter_1)
        self.verticalSlider_11.setMinimum(-100)
        self.verticalSlider_11.setMaximum(0)
        self.verticalSlider_11.setSingleStep(1)
        self.verticalSlider_11.setProperty("value", -20)
        self.verticalSlider_11.setSliderPosition(0)
        self.verticalSlider_11.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_11.setObjectName("verticalSlider_11")

        self.verticalSlider_12 = QtWidgets.QSlider(self.splitter_1)
        self.verticalSlider_12.setEnabled(True)
        self.verticalSlider_12.setMinimum(-100)
        self.verticalSlider_12.setMaximum(0)
        self.verticalSlider_12.setSingleStep(1)
        self.verticalSlider_12.setProperty("value", -100)
        self.verticalSlider_12.setSliderPosition(-100)
        self.verticalSlider_12.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_12.setObjectName("verticalSlider_12")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 725, 1200, 30))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reset = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.reset.setObjectName("reset")
        self.horizontalLayout.addWidget(self.reset)
      
        self.save = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)

        self.playb = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Icons/play.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playb.setIcon(icon8)
        self.playb.setIconSize(QtCore.QSize(20, 30))
        self.playb.setObjectName("playb")
        self.horizontalLayout.addWidget(self.playb)

        self.Zoomin = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/zoomin.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Zoomin.setIcon(icon1)
        self.Zoomin.setIconSize(QtCore.QSize(20, 30))
        self.Zoomin.setObjectName("Zoomin")
        self.horizontalLayout.addWidget(self.Zoomin)
        
        self.Zoomout = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/zoomout.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Zoomout.setIcon(icon2)
        self.Zoomout.setIconSize(QtCore.QSize(20, 30))
        self.Zoomout.setObjectName("Zoomout")
        self.horizontalLayout.addWidget(self.Zoomout)

        self.Clear = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/clear.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Clear.setIcon(icon3)
        self.Clear.setIconSize(QtCore.QSize(20, 30))
        self.Clear.setObjectName("Clear")
        self.horizontalLayout.addWidget(self.Clear)

        self.Scrollr = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Scrollr.setIcon(icon4)
        self.Scrollr.setIconSize(QtCore.QSize(20, 30))
        self.Scrollr.setObjectName("Scroll")
        self.horizontalLayout.addWidget(self.Scrollr)

        self.Scrolll = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Scrolll.setIcon(icon5)
        self.Scrolll.setIconSize(QtCore.QSize(20, 30))
        self.Scrolll.setObjectName("Scroll")
        self.horizontalLayout.addWidget(self.Scrolll)

        self.Scrollu = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icons/upp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Scrollu.setIcon(icon6)
        self.Scrollu.setIconSize(QtCore.QSize(20, 30))
        self.Scrollu.setObjectName("Scrollu")
        self.horizontalLayout.addWidget(self.Scrollu)

        self.Scrolld = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icons/Down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Scrolld.setIcon(icon7)
        self.Scrolld.setIconSize(QtCore.QSize(20, 30))
        self.Scrolld.setObjectName("Scrolld")
        self.horizontalLayout.addWidget(self.Scrolld)

        self.playa = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.playa.setIcon(icon8)
        self.playb.setIconSize(QtCore.QSize(20, 30))
        self.playa.setObjectName("playa")
        self.horizontalLayout.addWidget(self.playa)


        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("color palette1")
        self.comboBox.addItem("color palette2")
        self.comboBox.addItem("color palette3")
        self.comboBox.addItem("color palette4")
        self.comboBox.addItem("color palette5")
        self.horizontalLayout.addWidget(self.comboBox)

        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)

        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 15, 650, 230))
        self.graphicsView.setObjectName("graphicsView")

        self.graphicsView_2 = PlotWidget(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 485, 650, 230))
        self.graphicsView_2.setObjectName("graphicsView_2")

        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(670, 10, 550, 320))
        self.photo.setAutoFillBackground(False)
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("white.PNG"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")

        self.photo2 = QtWidgets.QLabel(self.centralwidget)
        self.photo2.setGeometry(QtCore.QRect(670, 375, 550, 320))
        self.photo2.setText("")
        self.photo2.setPixmap(QtGui.QPixmap("white.PNG"))
        self.photo2.setScaledContents(True)
        self.photo2.setObjectName("photo2")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionPrint)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.reset.setShortcut(_translate("MainWindow", "r"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.save.setShortcut(_translate("MainWindow", "s"))
        self.Zoomin.setToolTip(_translate("MainWindow", "Zoom in"))
        self.Zoomin.setShortcut(_translate("MainWindow", "z,i"))
        self.Zoomout.setToolTip(_translate("MainWindow", "Zoom out")) 
        self.Zoomout.setShortcut(_translate("MainWindow", "z,o")) 
        self.Clear.setToolTip(_translate("MainWindow", "Clear")) 
        self.Clear.setShortcut(_translate("MainWindow", "C")) 
        self.Scrollr.setToolTip(_translate("MainWindow", "Scrollr")) 
        self.Scrollr.setShortcut(_translate("MainWindow", "Ctrl+r")) 
        self.Scrolll.setToolTip(_translate("MainWindow", "Scrolll")) 
        self.Scrolll.setShortcut(_translate("MainWindow", "Ctrl+l"))
        self.Scrollu.setToolTip(_translate("MainWindow", "Scrollu")) 
        self.Scrollu.setShortcut(_translate("MainWindow", "Ctrl+u")) 
        self.Scrolld.setToolTip(_translate("MainWindow", "Scrolld")) 
        self.Scrolld.setShortcut(_translate("MainWindow", "Ctrl+d"))

        self.playb.setToolTip(_translate("MainWindow", "playb")) 
        self.playb.setShortcut(_translate("MainWindow", "Ctrl+b")) 
        self.playa.setToolTip(_translate("MainWindow", "playa")) 
        self.playa.setShortcut(_translate("MainWindow", "Ctrl+a"))

        self.comboBox.setItemText(0, _translate("MainWindow", "color palette1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "color palette2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "color palette3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "color palette4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "color palette5"))

        self.checkBox.setText(_translate("MainWindow", "Show/Hide"))
        self.checkBox.setShortcut(_translate("MainWindow", "h")) 
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+o"))
        self.actionPrint.setText(_translate("MainWindow", "print"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+p"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


